theme: jekyll-theme-cayman
docs:
  - title: Introduction
    url: /
  - title: Getting Started
    url: getting-started.html
  - title: Schema Definition
    url: schema-definition.html
  - title: Parsing, Validating and Executing
    url: parsing-validating-executing.html
  - title: Server
    url: server.html
